version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "sea.hub:5000/pause:3.6"
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/docker/certs.d/"
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."sea.hub:5000".tls]
          insecure_skip_verify = true
          ca_file = "/etc/docker/certs.d/sea.hub:5000/sea.hub.crt"