name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: startswith(github.event.comment.body, '/imagebuild')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Auto build image
        id: autobuild
        run: |
          commentbody="${{github.event.comment.body}}"
          version=`echo "$commentbody"|cut -d" " -f2`
          echo "start to build kubernetes:$version"
          sudo wget https://sealer.oss-cn-beijing.aliyuncs.com/auto-build/context.tar.gz && sudo tar -xvf context.tar.gz && cd context
          #amd64
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl -o ./amd64/bin/kubectl
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubelet -o ./amd64/bin/kubelet
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubeadm -o ./amd64/bin/kubeadm
          #arm64
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/arm64/kubectl -o ./arm64/bin/kubectl
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/arm64/kubelet -o ./arm64/bin/kubelet
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/arm64/kubeadm -o ./arm64/bin/kubeadm
          sudo wget https://sealer.oss-cn-beijing.aliyuncs.com/sealer-latest.tar.gz && sudo tar -xvf sealer-latest.tar.gz -C /usr/bin
          sudo sealer login ${{secrets.PRIVATEWAREHOUSE}}
          sudo sed -i "s/v1.19.8/$version/g" ./rootfs/etc/kubeadm.yml && sudo sed -i "s/v1.19.8/$version/g" ./calico/Kubefile
          sudo chmod +x ./amd64/bin/kubeadm && sudo ./amd64/bin/kubeadm config images list --config ./rootfs/etc/kubeadm.yml
          sudo ./amd64/bin/kubeadm config images list --config ./rootfs/etc/kubeadm.yml 2>/dev/null>> imageList
          sudo sed -i "s/k8s.gcr.io/sea.hub:5000/g" ./rootfs/etc/kubeadm.yml
          sudo sealer build -t kubernetes:$version-alpine --platform linux/arm64,linux/amd64
          sudo sealer push kubernetes:$version-alpine
          cd calico && sudo sealer build -t kubernetes:$version --platform linux/arm64,linux/amd64
          sudo sealer push kubernetes:$version
          echo "::set-output name=version::$version"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Image ${{ steps.autobuild.outputs.version }} build successfully!