name: markdownlink

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths:
      - '*.md'
jobs:
  lint-markdown-docs:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint markdown file
      uses: docker://avto-dev/markdown-lint:v1.5.0
      with:
        args: '*.md'
