on:
  issue_comment:
    types:
      - created
  push:
    tags:
      - 'test*'
name: Static page
jobs:
  build:
    if: ${{ (github.repository == 'bxy4543/sealer' && github.ref_type=='tag') || (github.event.issue.pull_request && github.event.comment.body == '/docs') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(github) }}
        run: echo "$STEPS_CONTEXT"